healths:
  BADLANDS: 125
  BAMBOO_JUNGLE: 550
  BEACH: 120
  BIRCH_FOREST: 400
  CHERRY_GROVE: 420
  COLD_OCEAN: -1
  CRIMSON_FOREST: 420
  DARK_FOREST: 500
  DEEP_COLD_OCEAN: -1
  DEEP_DARK: 100
  DEEP_FROZEN_OCEAN: -1
  DEEP_LUKEWARM_OCEAN: -1
  DEEP_OCEAN: -1
  DESERT: 100
  ERODED_BADLANDS: 110
  FLOWER_FOREST: 300
  FOREST: 325
  FROZEN_OCEAN: -1
  FROZEN_PEAKS: -1
  FROZEN_RIVER: -1
  GROVE: 10
  ICE_SPIKES: -1
  JAGGED_PEAKS: -1
  JUNGLE: 800
  LUKEWARM_OCEAN: -1
  LUSH_CAVES: 150
  MANGROVE_SWAMP: 1100
  MEADOW: 10
  MUSHROOM_FIELDS: 750
  OCEAN: -1
  OLD_GROWTH_BIRCH_FOREST: 101
  OLD_GROWTH_PINE_TAIGA: 101
  OLD_GROWTH_SPRUCE_TAIGA: 101
  PLAINS: 250
  RIVER: -1
  SAVANNA: 150
  SAVANNA_PLATEAU: 125
  SNOWY_BEACH: 15
  SNOWY_PLAINS: 15
  SNOWY_SLOPES: 15
  SNOWY_TAIGA: 50
  SPARSE_JUNGLE: 500
  STONY_PEAKS: 10
  STONY_SHORE: 10
  SUNFLOWER_PLAINS: 350
  SWAMP: 750
  TAIGA: 300
  WARM_OCEAN: -1
  WINDSWEPT_FOREST: 300
  WINDSWEPT_GRAVELLY_HILLS: 290
  WINDSWEPT_HILLS: 280
  WINDSWEPT_SAVANNA: 200
  WOODED_BADLANDS: 125
setup:
  regeneration: 10
  grow_damage: 5
  tree_damage: 10
  creature_damage: 5